In [1]:
import torch

In [7]:
x = torch.randn(3,requires_grad=True)
print(x)

tensor([-0.3316,  0.4318, -0.4024], requires_grad=True)


In [8]:
y = x+2
print(y)

tensor([1.6684, 2.4318, 1.5976], grad_fn=<AddBackward0>)


In [9]:
z = y*y*2
print(z)

tensor([ 5.5672, 11.8269,  5.1048], grad_fn=<MulBackward0>)


z=z.mean()
print(z)

z is not a scalar (single value). It is probably a tensor containing multiple values.

backward() can automatically calculate gradients only when the output is a single scalar.

Make z a scalar

Usually, use sum() or mean()

Give backward() the gradient manually

In [11]:
v = torch.ones_like(z)
z.backward(v)
print(x.grad)

tensor([6.6736, 9.7270, 6.3905])


*To prevent tracking gradient*

In [13]:
x1 = torch.tensor([1,5,8,9,16],dtype=torch.float32,requires_grad=True)
print(x1)

tensor([ 1.,  5.,  8.,  9., 16.], requires_grad=True)


In [15]:
x1.requires_grad_(False)
print(x1)

tensor([ 1.,  5.,  8.,  9., 16.])


In [17]:
# detach method
x2 = torch.tensor([7,8,9,5],dtype=torch.float32,requires_grad=True)
print(x2)
y = x2.detach()
print(y)

tensor([7., 8., 9., 5.], requires_grad=True)
tensor([7., 8., 9., 5.])


In [18]:
with torch.no_grad():
    y = x2+3
    print(y)

tensor([10., 11., 12.,  8.])


In [19]:
y = x2+1
print(y)

tensor([ 8.,  9., 10.,  6.], grad_fn=<AddBackward0>)
