In [1]:
import torch

In [2]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
print(x)

tensor([[0.1210, 0.8431, 0.9510, 0.9307, 0.0060, 0.8084, 0.6158, 0.2792, 0.3572,
         0.6146, 0.1861, 0.1891, 0.9936, 0.4052, 0.1503, 0.4068, 0.3178, 0.4366,
         0.9896, 0.0497, 0.2721, 0.9990, 0.6383, 0.3747, 0.9141],
        [0.6575, 0.2003, 0.5591, 0.2717, 0.7910, 0.9000, 0.3145, 0.7204, 0.8898,
         0.3163, 0.5622, 0.7199, 0.0662, 0.0938, 0.3155, 0.6500, 0.1126, 0.6473,
         0.6081, 0.8097, 0.7780, 0.3330, 0.7035, 0.9144, 0.1190],
        [0.5740, 0.1789, 0.4412, 0.9454, 0.6250, 0.3265, 0.6809, 0.9629, 0.5763,
         0.6032, 0.2967, 0.7988, 0.3675, 0.1937, 0.6966, 0.3577, 0.7411, 0.0702,
         0.0819, 0.6544, 0.3565, 0.5502, 0.7037, 0.9959, 0.2370],
        [0.1119, 0.5368, 0.3124, 0.0784, 0.3976, 0.5037, 0.1380, 0.5623, 0.0350,
         0.6036, 0.5314, 0.2786, 0.4393, 0.3281, 0.6076, 0.3307, 0.5215, 0.6906,
         0.2327, 0.0864, 0.6544, 0.2630, 0.1462, 0.6450, 0.5387],
        [0.0042, 0.8158, 0.0223, 0.1464, 0.5479, 0.2969, 0.8063, 0.3105, 0.0802,
       

In [3]:
print(x[0].shape)
print(x[:0].shape)
print(x[2, 0:10])

torch.Size([25])
torch.Size([0, 25])
tensor([0.5740, 0.1789, 0.4412, 0.9454, 0.6250, 0.3265, 0.6809, 0.9629, 0.5763,
        0.6032])


In [7]:
z = torch.tensor([[1,2,3,4,5],[6,7,8,9,10]])
print(z[0].shape)
print(z[:1].shape)

torch.Size([5])
torch.Size([1, 5])


*Fancy Indexing*

In [9]:
x = torch.arange(10)
print(x)
indices = [2,5,8]
print(x[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


In [13]:
x = torch.rand((3,5))
print(x)
row = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[row,cols])
print(x[row,cols].shape)

tensor([[0.4326, 0.9535, 0.7677, 0.7695, 0.9405],
        [0.2160, 0.2608, 0.2776, 0.2653, 0.0398],
        [0.3743, 0.5484, 0.3268, 0.7392, 0.2569]])
tensor([0.0398, 0.4326])
torch.Size([2])


*Advance Indexing*

In [15]:
x = torch.arange(10)
print(x[(x<2) | (x>8)])
print(x[(x<2) & (x>8)])
print(x[x.remainder(2) ==0])

tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


*Useful Operations*

In [16]:
print(torch.where(x>5,x,x*2))
print(torch.tensor([0,0,1,1,2,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10
