In [1]:
import torch

In [31]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

In [3]:
z1 = torch.empty(3)
torch.add(x,y,out=z1)

tensor([10., 10., 10.])

In [5]:
z2 = torch.add(x,y)
print(z2)

tensor([10, 10, 10])


In [6]:
z = x+y
print(z)

tensor([10, 10, 10])


In [14]:
t = torch.zeros(3)
t.add_(x)
print(t)

tensor([1., 2., 3.])


In [17]:
t += x
print(t)

tensor([3., 6., 9.])


In [7]:
z = x-y
print(z)

tensor([-8, -6, -4])


In [8]:
c1 = torch.empty(3)
torch.subtract(x,y, out=c1)

tensor([-8., -6., -4.])

In [9]:
c2 = torch.subtract(x,y)
print(c2)

tensor([-8, -6, -4])


In [10]:
d1 = torch.true_divide(x,y)
print(d1)

tensor([0.1111, 0.2500, 0.4286])


In [11]:
d = x/y
print(d)

tensor([0.1111, 0.2500, 0.4286])


In [12]:
f1 =torch.floor_divide(x,y)
print(f1)

tensor([0, 0, 0])


In [13]:
f = y//x
print(f)

tensor([9, 4, 2])


In [18]:
z = x.pow(2)
print(z)

tensor([1, 4, 9])


In [19]:
z1 = x**3
print(z1)

tensor([ 1,  8, 27])


In [32]:
z2 =x.pow_(y)
print(z2)

tensor([   1,  256, 2187])


In [34]:
z = x>0
print(z)

tensor([True, True, True])


In [35]:
z = x<0
print(z)

tensor([False, False, False])


*Matrix Multiplication*

In [36]:
x1 = torch.rand((2,5))
print(x1)
x2 = torch.rand((5,3))
print(x2)


tensor([[0.6141, 0.5024, 0.6733, 0.8046, 0.4714],
        [0.0255, 0.0821, 0.0296, 0.1568, 0.9623]])
tensor([[0.9725, 0.8472, 0.0159],
        [0.6386, 0.5934, 0.4931],
        [0.3064, 0.0339, 0.6664],
        [0.5017, 0.5813, 0.3568],
        [0.9413, 0.9254, 0.6469]])


In [37]:
x3 =torch.mm(x1,x2)
print(x3)

tensor([[1.9718, 1.7452, 1.2982],
        [1.0708, 1.0530, 0.7391]])


*Matrix Exponenziation*

In [39]:
y1 = torch.randint(0,5,(5,5))
print(y1)
c = y1.matrix_power(3)
print(c)

tensor([[3, 4, 2, 0, 3],
        [4, 3, 2, 3, 4],
        [4, 2, 2, 2, 0],
        [0, 2, 3, 2, 3],
        [0, 3, 0, 3, 3]])
tensor([[319, 431, 251, 299, 424],
        [392, 520, 305, 392, 512],
        [292, 352, 202, 240, 324],
        [224, 306, 197, 226, 304],
        [192, 288, 174, 240, 294]])


*Element wise Multiplication*

In [42]:
z = x*y
print(x)
print(y)
print(z)

tensor([   1,  256, 2187])
tensor([9, 8, 7])
tensor([    9,  2048, 15309])


*Dot Product*

In [43]:
z = torch.dot(x,y)
print(z)

tensor(17366)


*Batch Matrix Multiplication*

In [46]:
batch = 32
n = 10
m = 20
p = 30

t1 = torch.rand((batch,n,m))
t2 = torch.rand((batch,m,p))
out_bmm = torch.bmm(t1,t2)
print(out_bmm)

tensor([[[1.9876, 3.0524, 3.0510,  ..., 2.8041, 3.5957, 4.1720],
         [4.0882, 4.6854, 4.3264,  ..., 4.0577, 5.6482, 6.3687],
         [4.2093, 4.6534, 3.9834,  ..., 3.7740, 5.7126, 6.4111],
         ...,
         [5.1064, 6.0400, 5.0290,  ..., 5.1271, 7.0512, 7.4115],
         [3.7051, 4.5888, 4.1706,  ..., 4.0574, 6.0620, 6.4113],
         [4.0755, 4.2965, 3.8878,  ..., 4.8257, 5.6206, 6.5335]],

        [[5.3060, 4.5206, 4.3687,  ..., 4.8075, 4.3715, 5.3752],
         [5.3760, 4.2250, 3.8089,  ..., 4.2320, 3.5356, 4.3171],
         [5.1258, 4.4477, 3.5234,  ..., 4.1089, 3.8977, 4.1651],
         ...,
         [4.1756, 4.1160, 4.3139,  ..., 4.1968, 3.9412, 4.9741],
         [4.9534, 3.7726, 3.8955,  ..., 4.7629, 4.8188, 5.0351],
         [6.5560, 5.3953, 5.0281,  ..., 5.8186, 5.6879, 5.7252]],

        [[5.4187, 5.3538, 5.9307,  ..., 6.4076, 4.2548, 6.2872],
         [4.7182, 3.1894, 4.4159,  ..., 4.3021, 2.9040, 4.7664],
         [5.0136, 4.5510, 6.3344,  ..., 5.1148, 4.2140, 6.

*Examples of Broadcasting*

In [47]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z1 = x1-x2
print(z1)

z2 = x1**x2
print(z2)

tensor([[-0.0221, -0.8795,  0.1218, -0.2951,  0.2299],
        [ 0.2859, -0.1588, -0.6893,  0.2652,  0.8753],
        [-0.2081, -0.4598,  0.0160,  0.5387,  0.7351],
        [-0.0696, -0.0199, -0.0737, -0.0531, -0.0055],
        [-0.1142, -0.6409, -0.3596,  0.6223,  0.1928]])
tensor([[0.6921, 0.1148, 0.9498, 0.3883, 0.9569],
        [0.8879, 0.8347, 0.1862, 0.8461, 0.9968],
        [0.5413, 0.5352, 0.8614, 0.9669, 0.9913],
        [0.6569, 0.9726, 0.7849, 0.6538, 0.8883],
        [0.6220, 0.3542, 0.5279, 0.9993, 0.9522]])


In [49]:
sum_x = torch.sum(x, dim=0)
print(x)
print(sum_x)

tensor([   1,  256, 2187])
tensor(2444)


In [51]:
values ,indices = torch.max(x,dim=0)
print(values, indices)

tensor(2187) tensor(2)


In [52]:
values ,indices = torch.min(x,dim=0)
print(values, indices)

tensor(1) tensor(0)


In [53]:
abs_x = torch.abs(x)
print(abs_x)

tensor([   1,  256, 2187])


In [54]:
z =torch.argmax(x,dim=0)
print(z)

tensor(2)


In [55]:
z = torch.argmin(x,dim=0)
print(z)

tensor(0)


In [56]:
mean_x = torch.mean(x.float(), dim=0)
print(mean_x)

tensor(814.6667)


In [57]:
z = torch.eq(x,y)
print(z)

tensor([False, False, False])


In [59]:
sorted_y, indices = torch.sort(y,dim=0,descending=False)
print(sorted_y, indices)

tensor([7, 8, 9]) tensor([2, 1, 0])


In [60]:
z = torch.clamp(x, min=0, max=20)
print(z)

tensor([ 1, 20, 20])


In [61]:
x = torch.tensor([1,0,1,1,1], dtype=torch.bool)
print(x)

tensor([ True, False,  True,  True,  True])


In [62]:
z= torch.any(x)
print(z)

tensor(True)


In [63]:
z = torch.all(x)
print(z)

tensor(False)
