In [1]:
import torch

In [2]:
x = torch.arange(9)
x1 = x.view(3,3)
print(x1)
x2 = x.reshape(3,3)
print(x2)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [3]:
y = x2.t()
print(y)

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [5]:
print(y.contiguous().view(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [7]:
x1 = torch.rand(2,5)
x2 = torch.rand(2,5)
print(x1)
print(x2)

print(torch.cat((x1,x2),dim=0).shape)
print(torch.cat((x1,x2)))
print(torch.cat((x1,x2),dim=1).shape)

tensor([[0.6995, 0.4338, 0.7673, 0.9950, 0.1734],
        [0.8735, 0.2990, 0.4745, 0.0313, 0.0679]])
tensor([[0.5732, 0.7171, 0.7800, 0.3939, 0.3796],
        [0.7203, 0.2790, 0.0840, 0.5957, 0.9323]])
torch.Size([4, 5])
tensor([[0.6995, 0.4338, 0.7673, 0.9950, 0.1734],
        [0.8735, 0.2990, 0.4745, 0.0313, 0.0679],
        [0.5732, 0.7171, 0.7800, 0.3939, 0.3796],
        [0.7203, 0.2790, 0.0840, 0.5957, 0.9323]])
torch.Size([2, 10])


In [9]:
z = x1.view(-1)
print(z)
print(z.shape)

tensor([0.6995, 0.4338, 0.7673, 0.9950, 0.1734, 0.8735, 0.2990, 0.4745, 0.0313,
        0.0679])
torch.Size([10])


In [12]:
batch = 64
c = torch.rand((batch,2,5))
print(c)

tensor([[[0.3224, 0.9228, 0.4103, 0.3500, 0.8570],
         [0.0518, 0.6387, 0.4110, 0.3035, 0.0035]],

        [[0.4608, 0.3770, 0.1516, 0.1878, 0.9478],
         [0.0855, 0.5224, 0.7464, 0.2975, 0.2093]],

        [[0.2982, 0.4269, 0.8720, 0.8636, 0.8478],
         [0.1718, 0.1633, 0.5733, 0.3255, 0.7217]],

        [[0.6572, 0.7410, 0.3502, 0.5242, 0.2216],
         [0.8237, 0.3280, 0.7599, 0.2902, 0.6463]],

        [[0.0378, 0.6062, 0.2469, 0.6347, 0.2978],
         [0.9653, 0.2881, 0.6160, 0.8439, 0.8994]],

        [[0.7861, 0.3513, 0.3412, 0.8723, 0.7151],
         [0.7829, 0.3361, 0.6341, 0.3028, 0.9987]],

        [[0.7240, 0.9676, 0.1598, 0.6839, 0.4458],
         [0.9730, 0.8582, 0.2251, 0.1367, 0.1152]],

        [[0.6588, 0.9768, 0.2409, 0.6520, 0.3080],
         [0.1342, 0.9980, 0.8527, 0.5170, 0.5721]],

        [[0.8723, 0.1114, 0.6984, 0.1562, 0.6336],
         [0.3184, 0.5535, 0.4605, 0.2281, 0.0854]],

        [[0.9838, 0.6848, 0.6363, 0.1002, 0.3593],
         [0.3

In [13]:
d = c.view(batch,-1)
print(d)
print(d.shape)

tensor([[0.3224, 0.9228, 0.4103, 0.3500, 0.8570, 0.0518, 0.6387, 0.4110, 0.3035,
         0.0035],
        [0.4608, 0.3770, 0.1516, 0.1878, 0.9478, 0.0855, 0.5224, 0.7464, 0.2975,
         0.2093],
        [0.2982, 0.4269, 0.8720, 0.8636, 0.8478, 0.1718, 0.1633, 0.5733, 0.3255,
         0.7217],
        [0.6572, 0.7410, 0.3502, 0.5242, 0.2216, 0.8237, 0.3280, 0.7599, 0.2902,
         0.6463],
        [0.0378, 0.6062, 0.2469, 0.6347, 0.2978, 0.9653, 0.2881, 0.6160, 0.8439,
         0.8994],
        [0.7861, 0.3513, 0.3412, 0.8723, 0.7151, 0.7829, 0.3361, 0.6341, 0.3028,
         0.9987],
        [0.7240, 0.9676, 0.1598, 0.6839, 0.4458, 0.9730, 0.8582, 0.2251, 0.1367,
         0.1152],
        [0.6588, 0.9768, 0.2409, 0.6520, 0.3080, 0.1342, 0.9980, 0.8527, 0.5170,
         0.5721],
        [0.8723, 0.1114, 0.6984, 0.1562, 0.6336, 0.3184, 0.5535, 0.4605, 0.2281,
         0.0854],
        [0.9838, 0.6848, 0.6363, 0.1002, 0.3593, 0.3162, 0.2055, 0.5760, 0.8365,
         0.9669],
        [0

In [15]:
d = c.permute(0,2,1)
print(d)
print(d.shape)

tensor([[[0.3224, 0.0518],
         [0.9228, 0.6387],
         [0.4103, 0.4110],
         [0.3500, 0.3035],
         [0.8570, 0.0035]],

        [[0.4608, 0.0855],
         [0.3770, 0.5224],
         [0.1516, 0.7464],
         [0.1878, 0.2975],
         [0.9478, 0.2093]],

        [[0.2982, 0.1718],
         [0.4269, 0.1633],
         [0.8720, 0.5733],
         [0.8636, 0.3255],
         [0.8478, 0.7217]],

        [[0.6572, 0.8237],
         [0.7410, 0.3280],
         [0.3502, 0.7599],
         [0.5242, 0.2902],
         [0.2216, 0.6463]],

        [[0.0378, 0.9653],
         [0.6062, 0.2881],
         [0.2469, 0.6160],
         [0.6347, 0.8439],
         [0.2978, 0.8994]],

        [[0.7861, 0.7829],
         [0.3513, 0.3361],
         [0.3412, 0.6341],
         [0.8723, 0.3028],
         [0.7151, 0.9987]],

        [[0.7240, 0.9730],
         [0.9676, 0.8582],
         [0.1598, 0.2251],
         [0.6839, 0.1367],
         [0.4458, 0.1152]],

        [[0.6588, 0.1342],
         [0.97

In [22]:
e = torch.arange(10)
print(e.unsqueeze(0))
print(e.unsqueeze(0).shape)
print(e.unsqueeze(1))
print(e.unsqueeze(1).shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
torch.Size([10, 1])


In [23]:
f = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(f)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


In [27]:
g = f.squeeze(1)
print(g)
print(g.shape)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
torch.Size([1, 10])
