In [1]:
import torch

In [3]:
# creating an tensor

device ="cuda" if torch.cuda.is_available() else "cpu"

my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32, device="cpu", requires_grad=True)

print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [4]:
print(my_tensor.dtype)
print(my_tensor.shape)
print(my_tensor.device)
print(my_tensor.requires_grad)
print()

torch.float32
torch.Size([2, 3])
cpu
True



In [6]:
x = torch.empty(size=(3,3))
print(x)

tensor([[2.3601e+18, 2.0333e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [7]:
x = torch.zeros(size=(3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
x = torch.rand(size=(3, 3))
print(x)

tensor([[0.9608, 0.2303, 0.7367],
        [0.7581, 0.0017, 0.6711],
        [0.3603, 0.0051, 0.0449]])


In [9]:
x = torch.ones(size=(3, 3))
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [16]:
x = torch.eye(3, 3)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [18]:
x = torch.arange(start=0, end=5,step=1)
print(x)

tensor([0, 1, 2, 3, 4])


In [21]:
x = torch.linspace(start=0.1,end=1,steps=10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [22]:
x = torch.empty(size=(1,5)).normal_(mean=0, std=1)
print(x)

tensor([[-0.1650,  0.6449,  1.2596, -0.2062, -0.4243]])


In [23]:
x = torch.empty(size=(1,5)).uniform_(0,1)
print(x)

tensor([[0.5720, 0.0325, 0.2722, 0.5154, 0.4196]])


In [25]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [26]:
tensor = torch.arange(4)
print(tensor)

tensor([0, 1, 2, 3])


In [27]:
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


*array to tensor conversion & vice-versa*

In [30]:
import numpy as np

np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()

print(tensor)
print(np_array_back)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
